// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The request message for the CreateEnrollment method.
public struct CreateEnrollmentRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The parent collection in which to add this enrollment.
  public var parent: Swift.String = Swift.String()

  /// Required. The enrollment to create.
  public var enrollment: Enrollment? = nil

  /// Required. The user-provided ID to be assigned to the Enrollment. It should
  /// match the format `^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$`.
  public var enrollmentId: Swift.String = Swift.String()

  /// Optional. If set, validate the request and preview the review, but do not
  /// post it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateEnrollmentRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateEnrollmentRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let enrollment = CodingKeys(stringValue: "enrollment")
    static let enrollmentId = CodingKeys(stringValue: "enrollmentId")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "enrollment",
      "enrollmentId",
      "validateOnly",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.enrollment = try container.decodeIfPresent(Enrollment.self, forKey: .enrollment)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .enrollmentId) {
      self.enrollmentId = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.enrollment, forKey: .enrollment)
    try container.encode(self.enrollmentId, forKey: .enrollmentId)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.CreateEnrollmentRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
