// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a target of an invocation over HTTP.
public struct Destination: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Network config is used to configure how Eventarc resolves and
  /// connect to a destination.
  /// This should only be used with HttpEndpoint destination type.
  public var networkConfig: NetworkConfig? = nil

  public var descriptor: OneOf_Descriptor? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Destination`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Destination().with { $0.cloudRun = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cloudRun = CodingKeys(stringValue: "cloudRun")
    static let cloudFunction = CodingKeys(stringValue: "cloudFunction")
    static let gke = CodingKeys(stringValue: "gke")
    static let workflow = CodingKeys(stringValue: "workflow")
    static let httpEndpoint = CodingKeys(stringValue: "httpEndpoint")
    static let networkConfig = CodingKeys(stringValue: "networkConfig")

    static let _knownKeys: Set<Swift.String> = [
      "cloudRun",
      "cloudFunction",
      "gke",
      "workflow",
      "httpEndpoint",
      "networkConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.networkConfig = try container.decodeIfPresent(NetworkConfig.self, forKey: .networkConfig)

    var descriptor: OneOf_Descriptor? = nil
    let descriptorCheckAndSet = {
      if descriptor != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'descriptor'"))
      }
      descriptor = $0
    }
    if let cloudRun = try container.decodeIfPresent(CloudRun?.self, forKey: .cloudRun) {
      try descriptorCheckAndSet(.cloudRun(cloudRun))
    }
    if let cloudFunction = try container.decodeIfPresent(Swift.String.self, forKey: .cloudFunction)
    {
      try descriptorCheckAndSet(.cloudFunction(cloudFunction))
    }
    if let gke = try container.decodeIfPresent(GKE?.self, forKey: .gke) {
      try descriptorCheckAndSet(.gke(gke))
    }
    if let workflow = try container.decodeIfPresent(Swift.String.self, forKey: .workflow) {
      try descriptorCheckAndSet(.workflow(workflow))
    }
    if let httpEndpoint = try container.decodeIfPresent(HttpEndpoint?.self, forKey: .httpEndpoint) {
      try descriptorCheckAndSet(.httpEndpoint(httpEndpoint))
    }
    self.descriptor = descriptor
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.networkConfig, forKey: .networkConfig)

    if let choice = self.descriptor {
      switch choice {
      case .cloudRun(let value):
        try container.encode(value, forKey: .cloudRun)
      case .cloudFunction(let value):
        try container.encode(value, forKey: .cloudFunction)
      case .gke(let value):
        try container.encode(value, forKey: .gke)
      case .workflow(let value):
        try container.encode(value, forKey: .workflow)
      case .httpEndpoint(let value):
        try container.encode(value, forKey: .httpEndpoint)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_Descriptor: Codable, Equatable, Sendable {
    /// Cloud Run fully-managed resource that receives the events. The resource
    /// should be in the same project as the trigger.
    indirect case cloudRun(CloudRun?)
    /// The Cloud Function resource name. Cloud Functions V1 and V2 are
    /// supported.
    /// Format: `projects/{project}/locations/{location}/functions/{function}`
    ///
    /// This is a read-only field. Creating Cloud Functions V1/V2 triggers is
    /// only supported via the Cloud Functions product. An error will be returned
    /// if the user sets this value.
    case cloudFunction(Swift.String)
    /// A GKE service capable of receiving events. The service should be running
    /// in the same project as the trigger.
    indirect case gke(GKE?)
    /// The resource name of the Workflow whose Executions are triggered by
    /// the events. The Workflow resource should be deployed in the same project
    /// as the trigger.
    /// Format: `projects/{project}/locations/{location}/workflows/{workflow}`
    case workflow(Swift.String)
    /// An HTTP endpoint destination described by an URI.
    indirect case httpEndpoint(HttpEndpoint?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.Destination"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
