// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A representation of the event type resource.
public struct EventType: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The full name of the event type (for example,
  /// "google.cloud.storage.object.v1.finalized"). In the form of
  /// {provider-specific-prefix}.{resource}.{version}.{verb}. Types MUST be
  /// versioned and event schemas are guaranteed to remain backward compatible
  /// within one version. Note that event type versions and API versions do not
  /// need to match.
  public var type: Swift.String = Swift.String()

  /// Output only. Human friendly description of what the event type is about.
  /// For example "Bucket created in Cloud Storage".
  public var description: Swift.String = Swift.String()

  /// Output only. Filtering attributes for the event type.
  public var filteringAttributes: [FilteringAttribute] = []

  /// Output only. URI for the event schema.
  /// For example
  /// "https://github.com/googleapis/google-cloudevents/blob/master/proto/google/events/cloud/storage/v1/events.proto"
  public var eventSchemaUri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EventType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EventType().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "type")
    static let description = CodingKeys(stringValue: "description")
    static let filteringAttributes = CodingKeys(stringValue: "filteringAttributes")
    static let eventSchemaUri = CodingKeys(stringValue: "eventSchemaUri")

    static let _knownKeys: Set<Swift.String> = [
      "type",
      "description",
      "filteringAttributes",
      "eventSchemaUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(
      [FilteringAttribute].self, forKey: .filteringAttributes)
    {
      self.filteringAttributes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .eventSchemaUri) {
      self.eventSchemaUri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.filteringAttributes, forKey: .filteringAttributes)
    try container.encode(self.eventSchemaUri, forKey: .eventSchemaUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.EventType"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
