// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Filters events based on exact matches on the CloudEvents attributes.
public struct EventFilter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of a CloudEvents attribute. Currently, only a subset of
  /// attributes are supported for filtering. You can [retrieve a specific
  /// provider's supported event
  /// types](/eventarc/docs/list-providers#describe-provider).
  ///
  /// All triggers MUST provide a filter for the 'type' attribute.
  public var attribute: Swift.String = Swift.String()

  /// Required. The value for the attribute.
  public var value: Swift.String = Swift.String()

  /// Optional. The operator used for matching the events with the value of the
  /// filter. If not specified, only events that have an exact key-value pair
  /// specified in the filter are matched. The allowed values are `path_pattern`
  /// and `match-path-pattern`. `path_pattern` is only allowed for GCFv1
  /// triggers.
  public var `operator`: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EventFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EventFilter().with { $0.attribute = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let attribute = CodingKeys(stringValue: "attribute")
    static let value = CodingKeys(stringValue: "value")
    static let `operator` = CodingKeys(stringValue: "operator")

    static let _knownKeys: Set<Swift.String> = [
      "attribute",
      "value",
      "operator",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .attribute) {
      self.attribute = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .value) {
      self.value = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .`operator`) {
      self.`operator` = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.attribute, forKey: .attribute)
    try container.encode(self.value, forKey: .value)
    try container.encode(self.`operator`, forKey: .`operator`)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.EventFilter"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
