// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The configuration for Platform Telemetry logging for Eventarc Advanced
/// resources.
public struct LoggingConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The minimum severity of logs that will be sent to
  /// Stackdriver/Platform Telemetry. Logs at severitiy ≥ this value will be
  /// sent, unless it is NONE.
  public var logSeverity: LoggingConfig.LogSeverity = LoggingConfig.LogSeverity()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LoggingConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoggingConfig().with { $0.logSeverity = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let logSeverity = CodingKeys(stringValue: "logSeverity")

    static let _knownKeys: Set<Swift.String> = [
      "logSeverity"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      LoggingConfig.LogSeverity.self, forKey: .logSeverity)
    {
      self.logSeverity = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.logSeverity, forKey: .logSeverity)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The different severities for logging supported by Eventarc Advanced
  /// resources.
  /// This enum is an exhaustive list of log severities and is FROZEN. Do not
  /// expect new values to be added.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum LogSeverity: Codable, Equatable, Hashable, Sendable {
    /// Log severity is not specified. This value is treated the same as NONE,
    /// but is used to distinguish between no update and update to NONE in
    /// update_masks.
    case unspecified
    /// Default value at resource creation, presence of this value must be
    /// treated as no logging/disable logging.
    case `none`
    /// Debug or trace level logging.
    case debug
    /// Routine information, such as ongoing status or performance.
    case info
    /// Normal but significant events, such as start up, shut down, or a
    /// configuration change.
    case notice
    /// Warning events might cause problems.
    case warning
    /// Error events are likely to cause problems.
    case error
    /// Critical events cause more severe problems or outages.
    case critical
    /// A person must take action immediately.
    case alert
    /// One or more systems are unusable.
    case emergency
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`none`: return 1
      case .debug: return 2
      case .info: return 3
      case .notice: return 4
      case .warning: return 5
      case .error: return 6
      case .critical: return 7
      case .alert: return 8
      case .emergency: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "LOG_SEVERITY_UNSPECIFIED"
      case .`none`: return "NONE"
      case .debug: return "DEBUG"
      case .info: return "INFO"
      case .notice: return "NOTICE"
      case .warning: return "WARNING"
      case .error: return "ERROR"
      case .critical: return "CRITICAL"
      case .alert: return "ALERT"
      case .emergency: return "EMERGENCY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LogSeverity/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LOG_SEVERITY_UNSPECIFIED": self = .unspecified
      case "NONE": self = .`none`
      case "DEBUG": self = .debug
      case "INFO": self = .info
      case "NOTICE": self = .notice
      case "WARNING": self = .warning
      case "ERROR": self = .error
      case "CRITICAL": self = .critical
      case "ALERT": self = .alert
      case "EMERGENCY": self = .emergency
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LogSeverity/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`none`
      case 2: self = .debug
      case 3: self = .info
      case 4: self = .notice
      case 5: self = .warning
      case 6: self = .error
      case 7: self = .critical
      case 8: self = .alert
      case 9: self = .emergency
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("LOG_SEVERITY_UNSPECIFIED")
      case .`none`: return try container.encode("NONE")
      case .debug: return try container.encode("DEBUG")
      case .info: return try container.encode("INFO")
      case .notice: return try container.encode("NOTICE")
      case .warning: return try container.encode("WARNING")
      case .error: return try container.encode("ERROR")
      case .critical: return try container.encode("CRITICAL")
      case .alert: return try container.encode("ALERT")
      case .emergency: return try container.encode("EMERGENCY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.LoggingConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
