// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// MessageBus for the messages flowing through the system. The admin has
/// visibility and control over the messages being published and consumed and can
/// restrict publishers and subscribers to only a subset of data available in the
/// system by defining authorization policies.
public struct MessageBus: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Resource name of the form
  /// projects/{project}/locations/{location}/messageBuses/{message_bus}
  public var name: Swift.String = Swift.String()

  /// Output only. Server assigned unique identifier for the channel. The value
  /// is a UUID4 string and guaranteed to remain unchanged until the resource is
  /// deleted.
  public var uid: Swift.String = Swift.String()

  /// Output only. This checksum is computed by the server based on the value of
  /// other fields, and might be sent only on update and delete requests to
  /// ensure that the client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Output only. The creation time.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The last-modified time.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Resource labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Resource annotations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. Resource display name.
  public var displayName: Swift.String = Swift.String()

  /// Optional. Resource name of a KMS crypto key (managed by the user) used to
  /// encrypt/decrypt their event data.
  ///
  /// It must match the pattern
  /// `projects/*/locations/*/keyRings/*/cryptoKeys/*`.
  public var cryptoKeyName: Swift.String = Swift.String()

  /// Optional. Config to control Platform logging for the Message Bus. This log
  /// configuration is applied to the Message Bus itself, and all the Enrollments
  /// attached to it.
  public var loggingConfig: LoggingConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MessageBus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MessageBus().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let etag = CodingKeys(stringValue: "etag")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let cryptoKeyName = CodingKeys(stringValue: "cryptoKeyName")
    static let loggingConfig = CodingKeys(stringValue: "loggingConfig")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "etag",
      "createTime",
      "updateTime",
      "labels",
      "annotations",
      "displayName",
      "cryptoKeyName",
      "loggingConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cryptoKeyName) {
      self.cryptoKeyName = value
    }
    self.loggingConfig = try container.decodeIfPresent(LoggingConfig.self, forKey: .loggingConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.etag, forKey: .etag)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.cryptoKeyName, forKey: .cryptoKeyName)
    try container.encodeIfPresent(self.loggingConfig, forKey: .loggingConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.v1.MessageBus"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
